/**
 * 
 * Virtualization server to emulate API/service
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient', '../model/Virtualization'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Virtualization'));
  } else {
    // Browser globals (root is window)
    if (!root.SwaggerJsClient) {
      root.SwaggerJsClient = {};
    }
    root.SwaggerJsClient.VirtualizationResponse = factory(root.SwaggerJsClient.ApiClient, root.SwaggerJsClient.Virtualization);
  }
}(this, function(ApiClient, Virtualization) {
  'use strict';




  /**
   * The VirtualizationResponse model module.
   * @module model/VirtualizationResponse
   * @version 1.1.0
   */

  /**
   * Constructs a new <code>VirtualizationResponse</code>.
   * Virtualization  Response
   * @alias module:model/VirtualizationResponse
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>VirtualizationResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VirtualizationResponse} obj Optional instance to populate.
   * @return {module:model/VirtualizationResponse} The populated <code>VirtualizationResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('virtualizationList')) {
        obj['virtualizationList'] = ApiClient.convertToType(data['virtualizationList'], [Virtualization]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Virtualization>} virtualizationList
   */
  exports.prototype['virtualizationList'] = undefined;



  return exports;
}));


