/**
 * 
 * Virtualization server to emulate API/service
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient', '../model/Virtualization', '../model/VirtualizationResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Virtualization'), require('../model/VirtualizationResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.SwaggerJsClient) {
      root.SwaggerJsClient = {};
    }
    root.SwaggerJsClient.ReadyapiApi = factory(root.SwaggerJsClient.ApiClient, root.SwaggerJsClient.Virtualization, root.SwaggerJsClient.VirtualizationResponse);
  }
}(this, function(ApiClient, Virtualization, VirtualizationResponse) {
  'use strict';

  /**
   * Readyapi service.
   * @module api/ReadyapiApi
   * @version 1.1.0
   */

  /**
   * Constructs a new ReadyapiApi. 
   * @alias module:api/ReadyapiApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getVirtulizations operation.
     * @callback module:api/ReadyapiApi~getVirtulizationsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/VirtualizationResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get currently deployed virtualizations
     * 
     * @param {module:api/ReadyapiApi~getVirtulizationsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/VirtualizationResponse}
     */
    this.getVirtulizations = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = VirtualizationResponse;

      return this.apiClient.callApi(
        '/sv/v1/virtualizations', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the putVirtualization operation.
     * @callback module:api/ReadyapiApi~putVirtualizationCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Post test recipe
     * 
     * @param {String} virtualizationID 
     * @param {Object} opts Optional parameters
     * @param {module:model/Virtualization} opts.body 
     * @param {module:api/ReadyapiApi~putVirtualizationCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.putVirtualization = function(virtualizationID, opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];

      // verify the required parameter 'virtualizationID' is set
      if (virtualizationID == undefined || virtualizationID == null) {
        throw new Error("Missing the required parameter 'virtualizationID' when calling putVirtualization");
      }


      var pathParams = {
        'virtualizationID': virtualizationID
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/sv/v1/virtualizations/{virtualizationID}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
